### ISSUE TITLE
Specify login mode

### ISSUE THREAD

**Issue by kaitok** [userfront/toolkit#77]
I see that there is a way to show only the get login link at login, how do you implement this?
https://userfront.com/guide/automatic-login-form-react

**Comment by RJFelix** [comment]
Hi @kaitok, the Toolkit forms are configured via your Userfront dashboard, at (https://userfront.com/dashboard/authentication)[https://userfront.com/dashboard/authentication]. When you make changes to your auth configuration, they'll be automatically reflected in your toolkit shortly afterward. This means that once you've added a Toolkit form to your project, you can add, remove, or change authentication methods without needing to update your code.

Hope this helps! Let us know if we can answer any other questions for you.

**Comment by kaitok** [comment]
Thanks for reaching out, I tried that feature, but the login method did not change.

**Comment by isanchez-userfront** [comment]
Hey @kaitok apologies for the delayed response, it appears that page (https://userfront.com/guide/automatic-login-form-react) uses outdated images and doesn't reflect the most accurate appearance of the new toolkit with the configurations you're looking for. 

Take a look at our [toolkit storybook](https://vercel-toolkit-react-storybook.vercel.app/?path=/docs/views-select-factor--docs) to see a more accurate customizable preview with only email links as your only first factor.

![Screenshot 2024-01-16 at 8 15 17 PM](https://github.com/userfront/toolkit/assets/147533431/6c206699-1f4b-42ef-a7dc-259cd9d06318)

It should look like this when configured correctly with your workspace id from the dashboard.

I hope this helps! Please do not hesitate to reach out via our website for any support with the dashboard. We are always here and happy to help.
